# Generated by Django 2.0.7 on 2018-07-26 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_level', models.CharField(max_length=25)),
                ('co2_ppm', models.CharField(max_length=25)),
                ('soil_moisture', models.CharField(max_length=25)),
                ('air_temp', models.CharField(max_length=25)),
                ('air_humidity', models.CharField(max_length=25)),
                ('door_status', models.CharField(max_length=25)),
                ('growth_stage', models.CharField(max_length=25)),
                ('light_status', models.CharField(max_length=25)),
                ('current_time', models.DateTimeField(default=datetime.datetime(2018, 7, 26, 20, 34, 56, 685209))),
                ('fan_status', models.CharField(max_length=25)),
                ('solenoid1_status', models.CharField(max_length=25)),
                ('solenoid2_status', models.CharField(max_length=25)),
            ],
        ),
    ]
