# Generated by Django 2.0.7 on 2018-07-26 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantinfo', '0002_auto_20180726_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfo',
            name='current_time',
        ),
        migrations.AddField(
            model_name='plantinfo',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 20, 39, 4, 802131)),
        ),
    ]
