# Generated by Django 2.0.7 on 2018-07-26 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantinfo', '0003_auto_20180726_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfo',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 17, 28, 57, 688797)),
        ),
    ]
