# Generated by Django 2.0.7 on 2018-07-26 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantinfo', '0004_auto_20180726_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfo',
            name='fan_status',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='solenoid1_status',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='solenoid2_status',
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 19, 15, 35, 716014)),
        ),
    ]
